services:
  backend:  # Changed from 'api' to 'backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lamigo-backend  # Changed container name too
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@host.docker.internal:${DB_PORT}/${DB_NAME}
    volumes:
      - ./backend:/app
      - /app/env
      - /app/.venv