name: lamigo_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_svg: ^2.0.9

<<<<<<< HEAD
  # --- ADDED BY STUDENT B FOR AUTH & TRACKING ---
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_database: ^11.3.0
  flutter_secure_storage: ^9.2.2
  geolocator: ^13.0.1
  # ----------------------------------------------
=======
  #firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  flutter_secure_storage: ^9.0.0
>>>>>>> dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/