"""Initial LamiGo database schema

Revision ID: 69cf9491580d
Revises: 
Create Date: 2026-02-28 14:04:29.972556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cf9491580d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('org_id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('recipients',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('location_type', sa.Enum('HOME', 'APARTMENT', 'OFFICE', 'WAREHOUSE', 'RETAIL_STORE', 'OTHER', name='locationtype'), nullable=True),
    sa.Column('floor_number', sa.String(length=10), nullable=True),
    sa.Column('is_location_verified', sa.Boolean(), nullable=True),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_table('super_admins',
    sa.Column('admin_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'STATION_MANAGER', 'DRIVER', name='userrole'), nullable=True),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('branches',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('default_commission_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('delivery_preferences',
    sa.Column('preference_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'NEUTRAL', name='preferencestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.recipient_id'], ),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_table('packages',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('tracking_id', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('TO_BE_DELIVERED', 'DRAFT', 'SCHEDULED', 'ON_TRIP', 'DELIVERING_NOW', 'COMPLETED', 'FAILED', name='packagestatus'), nullable=True),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('sender_address', sa.Text(), nullable=True),
    sa.Column('package_photo_url', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_cod', sa.Boolean(), nullable=True),
    sa.Column('cod_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('delivery_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('num_of_attempts', sa.Integer(), server_default='0', nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.recipient_id'], ),
    sa.PrimaryKeyConstraint('package_id'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'STATION_MANAGER', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=50), nullable=True),
    sa.Column('nic_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nic_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.String(length=128), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.Enum('MOTORCYCLE', 'THREE_WHEEL', 'LORRY', name='vehicletype'), nullable=False),
    sa.Column('status', sa.Enum('OFF_DUTY', 'AVAILABLE', 'TRIP_SCHEDULED', 'ON_TRIP', 'ON_INCIDENT', 'INCIDENT_RESPONSE', name='driverstatus'), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('current_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('driver_financial_profiles',
    sa.Column('driver_id', sa.String(length=128), nullable=False),
    sa.Column('current_payable_balance', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('total_lifetime_earnings', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('total_lifetime_settled', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('last_settlement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_table('driver_settlements',
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.String(length=128), nullable=False),
    sa.Column('processed_by', sa.String(length=128), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_at_settlement', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', name='paymentmethod'), nullable=False),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('settlement_id')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=True),
    sa.Column('total_tasks_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('delivered_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_weight', sa.Numeric(precision=8, scale=2), server_default='0.00', nullable=True),
    sa.Column('total_cod_to_collect', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_return_time_scheduled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_return_time_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_return_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('delivery_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ON_TRIP', 'DELIVERING_NOW', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('estimated_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_type', sa.Enum('NOT_HOME', 'UNREACHABLE', 'RECIPIENT_REJECTED', 'CANCELLED_BY_RECIPIENT', 'CANCELLED_BY_MANAGER', 'CANCELLED_BY_DRIVER', name='failuretype'), nullable=True),
    sa.Column('failure_note', sa.Text(), nullable=True),
    sa.Column('proof_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.package_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('VEHICLE_BREAKDOWN', 'ACCIDENT', 'TRAFFIC_POLICE', 'MEDICAL_EMERGENCY', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_at_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('reported_at_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'INVESTIGATING', 'RESOLVED', name='incidentstatus'), nullable=True),
    sa.Column('handled_by', sa.String(length=128), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['handled_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('trip_commissions',
    sa.Column('commission_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.String(length=128), nullable=False),
    sa.Column('amount_earned', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('commission_id')
    )
    op.create_table('delivery_contexts',
    sa.Column('metadata_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('google_eta_seconds', sa.Integer(), nullable=True),
    sa.Column('google_dist_meters', sa.Integer(), nullable=True),
    sa.Column('rain_volume_1h', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['delivery_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('metadata_id')
    )
    op.create_table('incident_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('backup_driver_id', sa.String(length=128), nullable=False),
    sa.Column('assigned_by', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('HELP', 'PACKAGE_RESCUE', 'MECHANICAL_AID', 'OTHER', name='responsetype'), nullable=False),
    sa.Column('status', sa.Enum('DISPATCHED', 'ON_SITE', 'COMPLETED', 'CANCELLED', name='responsestatus'), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['backup_driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('task_instructions',
    sa.Column('instruction_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'VOICE_NOTE', name='instructiontype'), nullable=False),
    sa.Column('creator_role', sa.Enum('RECIPIENT', 'STATION_MANAGER', 'DRIVER', name='instructioncreator'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['delivery_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('instruction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_instructions')
    op.drop_table('incident_assignments')
    op.drop_table('delivery_contexts')
    op.drop_table('trip_commissions')
    op.drop_table('incidents')
    op.drop_table('delivery_tasks')
    op.drop_table('trips')
    op.drop_table('driver_settlements')
    op.drop_table('driver_financial_profiles')
    op.drop_table('drivers')
    op.drop_table('users')
    op.drop_table('packages')
    op.drop_table('delivery_preferences')
    op.drop_table('branches')
    op.drop_table('super_admins')
    op.drop_table('recipients')
    op.drop_table('organizations')
    # ### end Alembic commands ###
