"""fix: change DeliveryPreference FK from recipient_id to package_id

Revision ID: 80df4d25c98f
Revises: 24c49f4af0fd
Create Date: 2026-03-18 11:57:23.594528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80df4d25c98f'
down_revision: Union[str, Sequence[str], None] = '24c49f4af0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_preferences', sa.Column('package_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('delivery_preferences_recipient_id_fkey'), 'delivery_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_preferences', 'packages', ['package_id'], ['package_id'])
    op.drop_column('delivery_preferences', 'recipient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_preferences', sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'delivery_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_preferences_recipient_id_fkey'), 'delivery_preferences', 'recipients', ['recipient_id'], ['recipient_id'])
    op.drop_column('delivery_preferences', 'package_id')
    # ### end Alembic commands ###
