import 'package:flutter/material.dart';
<<<<<<< HEAD
import 'package:firebase_core/firebase_core.dart'; // Add this
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // REQUIRED: Initialize Firebase before running the app
=======
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'Features/Splash/Presentation/splash_screen.dart';
import 'Features/Auth/Presentation/login_screen.dart';
import 'Features/Home/Presentation/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
>>>>>>> dev
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
<<<<<<< HEAD
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'LamiGo Driver',
      theme: ThemeData.dark(),
      // Ensure your routes match your login logic
      initialRoute: '/',
      routes: {
        '/': (context) => const LoginScreen(),
        '/home': (context) => const HomeScreen(), // Student A usually builds this
      },
    );
  }
=======
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      routes: {
        '/': (context) => const SplashScreen(),
        '/login': (context) => const LoginScreen(),
        '/home': (context) => const HomeScreen(),
      },
    ),
  );
>>>>>>> dev
}